require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'WeatherAwear' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'WeatherAwearTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'WeatherAwear-tvOS' do
  # Pods for WeatherAwear-tvOS

  target 'WeatherAwear-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
